path:
  driver_path: C:\Users\kifunosato\Desktop\program\chromedriver-win32\chromedriver.exe
  move_path: C:\Users\kifunosato\Desktop\hotel_smart_importer\csv
  download_path: C:\Users\kifunosato\Downloads

get_data:
  selenium: true
  history: true
  onhand: true
  upload: true
  keep_local_csv: true
  manual_date: false #一度に取得できるのは3か月まで
  manual_history_start_date: '2026/06/07'
  manual_history_end_date: '2026/06/13'
  manual_onhand_start_date: '2026/06/14'
  manual_onhand_end_date: '2026/09/12'

facilities:
  - facility: kureha
    enabled: true
    facility_keyword: 紅葉
    export_facility_name: ヴィラ紅葉
    hotel_smart:
      url: https://connect.hotelsmart.jp/host/sales/csv-output
      id: xxxx
      pw: xxxx
    s3_info:
      bucket_name: onsen-jasper-importer-prod-data-xxxx
      access_key_id: 'xxxxx'
      secret_access_key: 'xxxxx'
      file_name: 'pms-reservations/kureha_'
